name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或者你希望部署的其他分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3  # 更新到 v3 版本

    - name: Set up Flutter
      uses: subosito/flutter-action@v2  # 更新到 v2 版本
      with:
        flutter-version: 3.22.1  # 确保使用最新 Flutter 版本

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run: flutter build web --release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4  # 更新到 v4 版本
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
